use std::fmt::Display;

#[derive(Clone)]
pub struct Opcode {
    pub name: &'static str,
    pub start_byte: u8,
    pub size: u8,
}

impl Display for Opcode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "op: {}, sb: 0x{:02X}, ac: {}",
            self.name, self.start_byte, self.size
        )
    }
}

#[macro_export]
macro_rules! opcode {
    ($name:expr, $start_byte:expr, $arg_count:expr) => {
        Opcode {
            name: $name,
            start_byte: $start_byte,
            size: $arg_count,
        }
    };
}

pub const OPCODES: &[Opcode] = &[
    opcode!("NOP", 0x00, 1),
    opcode!("LXI B,D16", 0x01, 3),
    opcode!("STAX B", 0x02, 1),
    opcode!("INX B", 0x03, 1),
    opcode!("INR B", 0x04, 1),
    opcode!("DCR B", 0x05, 1),
    opcode!("MVI B, D8", 0x06, 2),
    opcode!("RLC", 0x07, 1),
    opcode!("UNKNOWN", 0x08, 1),
    opcode!("DAD B", 0x09, 1),
    opcode!("LDAX B", 0x0a, 1),
    opcode!("DCX B", 0x0b, 1),
    opcode!("INR C", 0x0c, 1),
    opcode!("DCR C", 0x0d, 1),
    opcode!("MVI C,D8", 0x0e, 2),
    opcode!("RRC", 0x0f, 1),
    opcode!("UNKNOWN", 0x10, 1),
    opcode!("LXI D,D16", 0x11, 3),
    opcode!("STAX D", 0x12, 1),
    opcode!("INX D", 0x13, 1),
    opcode!("INR D", 0x14, 1),
    opcode!("DCR D", 0x15, 1),
    opcode!("MVI D, D8", 0x16, 2),
    opcode!("RAL", 0x17, 1),
    opcode!("UNKNOWN", 0x18, 1),
    opcode!("DAD D", 0x19, 1),
    opcode!("LDAX D", 0x1a, 1),
    opcode!("DCX D", 0x1b, 1),
    opcode!("INR E", 0x1c, 1),
    opcode!("DCR E", 0x1d, 1),
    opcode!("MVI E,D8", 0x1e, 2),
    opcode!("RAR", 0x1f, 1),
    opcode!("RIM", 0x20, 1),
    opcode!("LXI H,D16", 0x21, 3),
    opcode!("SHLD adr", 0x22, 3),
    opcode!("INX H", 0x23, 1),
    opcode!("INR H", 0x24, 1),
    opcode!("DCR H", 0x25, 1),
    opcode!("MVI H,D8", 0x26, 2),
    opcode!("DAA", 0x27, 1),
    opcode!("UNKNOWN", 0x28, 1),
    opcode!("DAD H", 0x29, 1),
    opcode!("LHLD adr", 0x2a, 3),
    opcode!("DCX H", 0x2b, 1),
    opcode!("INR L", 0x2c, 1),
    opcode!("DCR L", 0x2d, 1),
    opcode!("MVI L, D8", 0x2e, 2),
    opcode!("CMA", 0x2f, 1),
    opcode!("SIM", 0x30, 1),
    opcode!("LXI SP, D16", 0x31, 3),
    opcode!("STA adr", 0x32, 3),
    opcode!("INX SP", 0x33, 1),
    opcode!("INR M", 0x34, 1),
    opcode!("DCR M", 0x35, 1),
    opcode!("MVI M,D8", 0x36, 2),
    opcode!("STC", 0x37, 1),
    opcode!("UNKNOWN", 0x38, 1),
    opcode!("DAD SP", 0x39, 1),
    opcode!("LDA adr", 0x3a, 3),
    opcode!("DCX SP", 0x3b, 1),
    opcode!("INR A", 0x3c, 1),
    opcode!("DCR A", 0x3d, 1),
    opcode!("MVI A,D8", 0x3e, 2),
    opcode!("CMC", 0x3f, 1),
    opcode!("MOV B,B", 0x40, 1),
    opcode!("MOV B,C", 0x41, 1),
    opcode!("MOV B,D", 0x42, 1),
    opcode!("MOV B,E", 0x43, 1),
    opcode!("MOV B,H", 0x44, 1),
    opcode!("MOV B,L", 0x45, 1),
    opcode!("MOV B,M", 0x46, 1),
    opcode!("MOV B,A", 0x47, 1),
    opcode!("MOV C,B", 0x48, 1),
    opcode!("MOV C,C", 0x49, 1),
    opcode!("MOV C,D", 0x4a, 1),
    opcode!("MOV C,E", 0x4b, 1),
    opcode!("MOV C,H", 0x4c, 1),
    opcode!("MOV C,L", 0x4d, 1),
    opcode!("MOV C,M", 0x4e, 1),
    opcode!("MOV C,A", 0x4f, 1),
    opcode!("MOV D,B", 0x50, 1),
    opcode!("MOV D,C", 0x51, 1),
    opcode!("MOV D,D", 0x52, 1),
    opcode!("MOV D,E", 0x53, 1),
    opcode!("MOV D,H", 0x54, 1),
    opcode!("MOV D,L", 0x55, 1),
    opcode!("MOV D,M", 0x56, 1),
    opcode!("MOV D,A", 0x57, 1),
    opcode!("MOV E,B", 0x58, 1),
    opcode!("MOV E,C", 0x59, 1),
    opcode!("MOV E,D", 0x5a, 1),
    opcode!("MOV E,E", 0x5b, 1),
    opcode!("MOV E,H", 0x5c, 1),
    opcode!("MOV E,L", 0x5d, 1),
    opcode!("MOV E,M", 0x5e, 1),
    opcode!("MOV E,A", 0x5f, 1),
    opcode!("MOV H,B", 0x60, 1),
    opcode!("MOV H,C", 0x61, 1),
    opcode!("MOV H,D", 0x62, 1),
    opcode!("MOV H,E", 0x63, 1),
    opcode!("MOV H,H", 0x64, 1),
    opcode!("MOV H,L", 0x65, 1),
    opcode!("MOV H,M", 0x66, 1),
    opcode!("MOV H,A", 0x67, 1),
    opcode!("MOV L,B", 0x68, 1),
    opcode!("MOV L,C", 0x69, 1),
    opcode!("MOV L,D", 0x6a, 1),
    opcode!("MOV L,E", 0x6b, 1),
    opcode!("MOV L,H", 0x6c, 1),
    opcode!("MOV L,L", 0x6d, 1),
    opcode!("MOV L,M", 0x6e, 1),
    opcode!("MOV L,A", 0x6f, 1),
    opcode!("MOV M,B", 0x70, 1),
    opcode!("MOV M,C", 0x71, 1),
    opcode!("MOV M,D", 0x72, 1),
    opcode!("MOV M,E", 0x73, 1),
    opcode!("MOV M,H", 0x74, 1),
    opcode!("MOV M,L", 0x75, 1),
    opcode!("HLT", 0x76, 1),
    opcode!("MOV M,A", 0x77, 1),
    opcode!("MOV A,B", 0x78, 1),
    opcode!("MOV A,C", 0x79, 1),
    opcode!("MOV A,D", 0x7a, 1),
    opcode!("MOV A,E", 0x7b, 1),
    opcode!("MOV A,H", 0x7c, 1),
    opcode!("MOV A,L", 0x7d, 1),
    opcode!("MOV A,M", 0x7e, 1),
    opcode!("MOV A,A", 0x7f, 1),
    opcode!("ADD B", 0x80, 1),
    opcode!("ADD C", 0x81, 1),
    opcode!("ADD D", 0x82, 1),
    opcode!("ADD E", 0x83, 1),
    opcode!("ADD H", 0x84, 1),
    opcode!("ADD L", 0x85, 1),
    opcode!("ADD M", 0x86, 1),
    opcode!("ADD A", 0x87, 1),
    opcode!("ADC B", 0x88, 1),
    opcode!("ADC C", 0x89, 1),
    opcode!("ADC D", 0x8a, 1),
    opcode!("ADC E", 0x8b, 1),
    opcode!("ADC H", 0x8c, 1),
    opcode!("ADC L", 0x8d, 1),
    opcode!("ADC M", 0x8e, 1),
    opcode!("ADC A", 0x8f, 1),
    opcode!("SUB B", 0x90, 1),
    opcode!("SUB C", 0x91, 1),
    opcode!("SUB D", 0x92, 1),
    opcode!("SUB E", 0x93, 1),
    opcode!("SUB H", 0x94, 1),
    opcode!("SUB L", 0x95, 1),
    opcode!("SUB M", 0x96, 1),
    opcode!("SUB A", 0x97, 1),
    opcode!("SBB B", 0x98, 1),
    opcode!("SBB C", 0x99, 1),
    opcode!("SBB D", 0x9a, 1),
    opcode!("SBB E", 0x9b, 1),
    opcode!("SBB H", 0x9c, 1),
    opcode!("SBB L", 0x9d, 1),
    opcode!("SBB M", 0x9e, 1),
    opcode!("SBB A", 0x9f, 1),
    opcode!("ANA B", 0xa0, 1),
    opcode!("ANA C", 0xa1, 1),
    opcode!("ANA D", 0xa2, 1),
    opcode!("ANA E", 0xa3, 1),
    opcode!("ANA H", 0xa4, 1),
    opcode!("ANA L", 0xa5, 1),
    opcode!("ANA M", 0xa6, 1),
    opcode!("ANA A", 0xa7, 1),
    opcode!("XRA B", 0xa8, 1),
    opcode!("XRA C", 0xa9, 1),
    opcode!("XRA D", 0xaa, 1),
    opcode!("XRA E", 0xab, 1),
    opcode!("XRA H", 0xac, 1),
    opcode!("XRA L", 0xad, 1),
    opcode!("XRA M", 0xae, 1),
    opcode!("XRA A", 0xaf, 1),
    opcode!("ORA B", 0xb0, 1),
    opcode!("ORA C", 0xb1, 1),
    opcode!("ORA D", 0xb2, 1),
    opcode!("ORA E", 0xb3, 1),
    opcode!("ORA H", 0xb4, 1),
    opcode!("ORA L", 0xb5, 1),
    opcode!("ORA M", 0xb6, 1),
    opcode!("ORA A", 0xb7, 1),
    opcode!("CMP B", 0xb8, 1),
    opcode!("CMP C", 0xb9, 1),
    opcode!("CMP D", 0xba, 1),
    opcode!("CMP E", 0xbb, 1),
    opcode!("CMP H", 0xbc, 1),
    opcode!("CMP L", 0xbd, 1),
    opcode!("CMP M", 0xbe, 1),
    opcode!("CMP A", 0xbf, 1),
    opcode!("RNZ", 0xc0, 1),
    opcode!("POP B", 0xc1, 1),
    opcode!("JNZ adr", 0xc2, 3),
    opcode!("JMP adr", 0xc3, 3),
    opcode!("CNZ adr", 0xc4, 3),
    opcode!("PUSH B", 0xc5, 1),
    opcode!("ADI D8", 0xc6, 2),
    opcode!("RST 0", 0xc7, 1),
    opcode!("RZ", 0xc8, 1),
    opcode!("RET", 0xc9, 1),
    opcode!("JZ adr", 0xca, 3),
    opcode!("UNKNOWN", 0xcb, 1),
    opcode!("CZ adr", 0xcc, 3),
    opcode!("CALL adr", 0xcd, 3),
    opcode!("ACI D8", 0xce, 2),
    opcode!("RST 1", 0xcf, 1),
    opcode!("RNC", 0xd0, 1),
    opcode!("POP D", 0xd1, 1),
    opcode!("JNC adr", 0xd2, 3),
    opcode!("OUT D8", 0xd3, 2),
    opcode!("CNC adr", 0xd4, 3),
    opcode!("PUSH D", 0xd5, 1),
    opcode!("SUI D8", 0xd6, 2),
    opcode!("RST 2", 0xd7, 1),
    opcode!("RC", 0xd8, 1),
    opcode!("UNKNOWN", 0xd9, 1),
    opcode!("JC adr", 0xda, 3),
    opcode!("IN D8", 0xdb, 2),
    opcode!("CC adr", 0xdc, 3),
    opcode!("UNKNOWN", 0xdd, 1),
    opcode!("SBI D8", 0xde, 2),
    opcode!("RST 3", 0xdf, 1),
    opcode!("RPO", 0xe0, 1),
    opcode!("POP H", 0xe1, 1),
    opcode!("JPO adr", 0xe2, 3),
    opcode!("XTHL", 0xe3, 1),
    opcode!("CPO adr", 0xe4, 3),
    opcode!("PUSH H", 0xe5, 1),
    opcode!("ANI D8", 0xe6, 2),
    opcode!("RST 4", 0xe7, 1),
    opcode!("RPE", 0xe8, 1),
    opcode!("PCHL", 0xe9, 1),
    opcode!("JPE adr", 0xea, 3),
    opcode!("XCHG", 0xeb, 1),
    opcode!("CPE adr", 0xec, 3),
    opcode!("UNKNOWN", 0xed, 1),
    opcode!("XRI D8", 0xee, 2),
    opcode!("RST 5", 0xef, 1),
    opcode!("RP", 0xf0, 1),
    opcode!("POP PSW", 0xf1, 1),
    opcode!("JP adr", 0xf2, 3),
    opcode!("DI", 0xf3, 1),
    opcode!("CP adr", 0xf4, 3),
    opcode!("PUSH PSW", 0xf5, 1),
    opcode!("ORI D8", 0xf6, 2),
    opcode!("RST 6", 0xf7, 1),
    opcode!("RM", 0xf8, 1),
    opcode!("SPHL", 0xf9, 1),
    opcode!("JM adr", 0xfa, 3),
    opcode!("EI", 0xfb, 1),
    opcode!("CM adr", 0xfc, 3),
    opcode!("UNKNOWN", 0xfd, 1),
    opcode!("CPI D8", 0xfe, 2),
    opcode!("RST 7", 0xff, 1),
];
